# -*- coding: utf-8 -*-
# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="sshuttle",
    version="0.2.1",
    description="sshuttle is an ssh vehicle for your environment",
    python_requires="==3.*,>=3.6.0",
    author="Justin Kinney",
    author_email="justin.kinney@oracle.com",
    entry_points={"console_scripts": ["sshuttle = sshuttle.cli:cli"]},
    packages=["sshuttle"],
    package_dir={"": "."},
    package_data={},
    install_requires=[],
)
